### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xubaoguo** [IsNott/spring-cloud-security-cli#1]
java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
![WX20240530-173312](https://github.com/IsNott/spring-cloud-security-cli/assets/6970524/12d30fbf-ef32-4b57-a672-a3eaeb6e42df)

**Comment by IsNott** [comment]
re: 降低JDK版本至17
